var element1 = document.querySelector('.sell__menu .sell__menu-list:nth-child(1)')
var element2 = document.querySelector('.sell__menu .sell__menu-list:nth-child(2)')
var element1 = document.querySelector('.sell__menu .sell__menu-list:nth-child(3)')
var element1 = document.querySelector('.sell__menu .sell__menu-list:nth-child(4)')
console.log(element1)