var element1 = document.querySelector('.sell__menu .sell__menu-list:nth-child(1)')
var element1 = document.querySelector('.sell__menu .sell__menu-list:nth-child(1)')
var element1 = document.querySelector('.sell__menu .sell__menu-list:nth-child(1)')
var element1 = document.querySelector('.sell__menu .sell__menu-list:nth-child(1)')
console.log(element1)